name: Lint Code Base

on: [push, pull_request]

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 .
